#!/bin/bash
# Script to help generate PWA icons and screenshots

echo "🎨 PWA Icon & Screenshot Generator"
echo "=================================="
echo ""
echo "This guide helps you create icons needed for PWA:"
echo ""
echo "Required Icons (place in public/ folder):"
echo "1. favicon.ico - 32x32 pixels"
echo "2. apple-touch-icon.png - 180x180 pixels"
echo "3. icon-192.png - 192x192 pixels"
echo "4. icon-192-maskable.png - 192x192 pixels (with padding)"
echo "5. icon-512.png - 512x512 pixels"
echo "6. icon-512-maskable.png - 512x512 pixels (with padding)"
echo "7. icon-96.png - 96x96 pixels"
echo ""
echo "Optional Screenshots (for app stores):"
echo "8. screenshot-1.png - 540x720 pixels (mobile)"
echo "9. screenshot-2.png - 1280x720 pixels (desktop)"
echo ""
echo "Tools to Create Icons:"
echo "- Figma (https://figma.com) - Design tool"
echo "- Real Favicon Generator (https://realfavicongenerator.net)"
echo "- Maskable (https://maskable.app) - Create maskable icons"
echo "- TinyPNG (https://tinypng.com) - Compress images"
echo ""
echo "Steps:"
echo "1. Create your app logo/icon (1024x1024 minimum)"
echo "2. Use Real Favicon Generator to create all sizes"
echo "3. Use Maskable.app to create maskable versions"
echo "4. Place all PNG files in public/ folder"
echo "5. Keep favicon.ico for browser compatibility"
echo ""
echo "Maskable Icon Tips:"
echo "- Must have at least 20% padding"
echo "- Safe zone diameter: 66% of viewBox"
echo "- Transparent background"
echo "- Solid colors work best"
echo ""
echo "Screenshot Tips:"
echo "- Show main features of your app"
echo "- Add text overlays with key information"
echo "- Use consistent styling and colors"
echo "- Mobile: portrait orientation (540x720)"
echo "- Desktop: landscape orientation (1280x720)"
